### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by 2b3pro** [US-Artificial-Intelligence/abbey#10]
`Access to fetch at 'http://localhost:5000/feed/art-history' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

… in the browser.

Also, couldn't change the ports. Even if I changed settings.yml and rebuilt, they still use :3000 and :5000. I have other stuff on those ports. My changes show in the config files in Docker Desktop, but the app still calls your defaults.

**Comment by gkamer8** [comment]
Hi- thanks for filing an issue! Changing the ports would require also changing the docker compose file, so if you wanted to access the backend at port 1234 instead of 5000, you would need to change the backend service like so:

```
backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "1234:5000"
```
...in addition to changing the settings.yml file. Note that the internal URL remains the same. I'll update the README so that's clearer. If you're using the prod version, make sure the change is in the docker-compose.prod.yml file (otherwise, make the change in the docker-compose.yml file)

If you have something else running at port 5000, that could also explain the CORS issue. If that's still happening, please let me know!

EDIT: If any more issues, visit the backend URL in the browser (http://localhost:5000 or whatever you chose it to be) and make sure it's up and running. If it's not running, please include the docker logs before it shut down in your response!

**Comment by 2b3pro** [comment]
Okay, I got it working. Thank you!
